### ISSUE TITLE
Typo "receipe"

### ISSUE THREAD

**Issue by endolith** [mustvlad/ChatGPT-System-Prompts#1]
https://github.com/mustvlad/ChatGPT-System-Prompts#utility

> 
> [Python Debugger](https://github.com/mustvlad/ChatGPT-System-Prompts/blob/main/prompts/utility/python-debugger.md)
> [Receipe Recommender](https://github.com/mustvlad/ChatGPT-System-Prompts/blob/main/prompts/utility/receipe-recommender.md)
> [SQL Terminal](https://github.com/mustvlad/ChatGPT-System-Prompts/blob/main/prompts/utility/sql-terminal.md)
> 

https://github.com/mustvlad/ChatGPT-System-Prompts/blob/main/prompts/utility/receipe-recommender.md

**Comment by mustvlad** [comment]
Thanks! Merged the request.
